# TypeSpec POC — schema/ (inputs) vs src/ (interpreter)
#
# Build flow:
#   1. tsp compile   — validate schema, emit outputs (SpiceDB, metadata, JSON Schema)
#
# Layout: schema/ = adopter modules + main.tsp | lib/ = platform .tsp | src/ = interpreter (TS)
# Evaluators: `make demo` or `make run` → all output modes via tsp compile.
# `make samples` → refresh samples/demo-output.txt

TSP       := npx tsp
MAIN_TSP  := schema/main.tsp
SAMPLES   := samples/demo-output.txt
EMIT_OPT  = --option typespec-as-schema.output-format

.PHONY: all clean build compile emit-spicedb emit-metadata demo run samples

all: build compile

build:
	npx tsc -p tsconfig.build.json

compile: build
	$(TSP) compile $(MAIN_TSP)

emit-spicedb: build
	$(TSP) compile $(MAIN_TSP) $(EMIT_OPT)=spicedb

emit-metadata: build
	$(TSP) compile $(MAIN_TSP) $(EMIT_OPT)=metadata

demo: build
	@echo "=== SpiceDB / Zed ======================================================"
	@$(TSP) compile $(MAIN_TSP) $(EMIT_OPT)=spicedb 2>/dev/null
	@echo ""
	@echo "=== Service metadata (JSON) ============================================"
	@$(TSP) compile $(MAIN_TSP) $(EMIT_OPT)=metadata 2>/dev/null
	@echo ""
	@echo "=== Unified JSON Schema ================================================"
	@$(TSP) compile $(MAIN_TSP) $(EMIT_OPT)=unified-jsonschema 2>/dev/null
	@echo ""

run: demo

samples:
	@echo "# Generated by: make samples (same as make demo, captured to file)" > $(SAMPLES)
	@echo "# Regenerate: make samples" >> $(SAMPLES)
	@echo "" >> $(SAMPLES)
	@$(MAKE) demo >> $(SAMPLES) 2>&1

clean:
	rm -rf tsp-output/ dist/
