# TypeSpec POC — schema/ (inputs) vs src/ (interpreter)
#
# Build flow:
#   1. tsp compile   — validate schema, emit JSON Schema (tsp-output/)
#   2. emit-ir       — walk type graph → go-loader-example/schema/resources.json
#   3. go-build      — Go binary with embedded IR
#
# Layout: schema/ = adopter modules + main.tsp | lib/ = platform .tsp | src/ = interpreter (TS)
# Evaluators: `make demo` or `make run` → all 5 output modes on stdout.
# `make samples` → refresh samples/demo-output.txt
# Go consumer: `make run-consumer` (no Node at runtime for the binary).

TSP       := npx tsp
TSX       := npx tsx
EMITTER   := src/spicedb-emitter.ts
MAIN_TSP  := schema/main.tsp
IR_OUT    := go-loader-example/schema/resources.json
GO_BIN    := go-loader-example/bin/schema-consumer
SAMPLES   := samples/demo-output.txt

.PHONY: all clean build compile emit-ir emit-spicedb emit-metadata demo run samples run-consumer go-build

all: build compile emit-ir go-build

build:
	npx tsc -p tsconfig.build.json

compile: build
	$(TSP) compile $(MAIN_TSP)

emit-ir:
	$(TSX) $(EMITTER) $(MAIN_TSP) --ir $(IR_OUT)

go-build:
	cd go-loader-example && go build -o bin/schema-consumer .

# End-to-end console tour for reviewers (matches ts-as-schema POC pattern)
demo:
	@echo "=== SpiceDB / Zed ======================================================"
	@$(TSX) $(EMITTER) $(MAIN_TSP) 2>/dev/null
	@echo ""
	@echo "=== Service metadata (JSON) ============================================"
	@$(TSX) $(EMITTER) $(MAIN_TSP) --metadata 2>/dev/null
	@echo ""
	@echo "=== Unified JSON Schema ================================================"
	@$(TSX) $(EMITTER) $(MAIN_TSP) --unified-jsonschema 2>/dev/null
	@echo ""
	@echo "=== Annotations ========================================================"
	@$(TSX) $(EMITTER) $(MAIN_TSP) --annotations 2>/dev/null
	@echo ""
	@echo "=== Preview: inventory_host_view ========================================"
	@$(TSX) $(EMITTER) $(MAIN_TSP) --preview inventory_host_view 2>/dev/null
	@echo ""

# Alias for evaluators (plan: make run / make demo)
run: demo

# Regenerate checked-in sample capture (ts-as-schema POC pattern)
samples:
	@echo "# Generated by: make samples (same as make demo, captured to file)" > $(SAMPLES)
	@echo "# Regenerate: make samples" >> $(SAMPLES)
	@echo "" >> $(SAMPLES)
	@$(MAKE) demo >> $(SAMPLES) 2>&1

run-consumer: go-build
	./go-loader-example/bin/schema-consumer

emit-spicedb:
	$(TSX) $(EMITTER) $(MAIN_TSP)

emit-metadata:
	$(TSX) $(EMITTER) $(MAIN_TSP) --metadata

clean:
	rm -f $(IR_OUT) $(GO_BIN)
	rm -rf tsp-output/ dist/
