// defineProvider — reduces extension provider boilerplate.
//
// Provider authors supply only their expansion logic and metadata;
// discovery is auto-generated from the template definitions using
// the same discoverExtensionInstances utility the platform provides.

import type { Program } from "@typespec/compiler";
import type { ResourceDef } from "./types.js";
import type { ExtensionTemplateDef } from "./registry.js";
import type { ExtensionProvider, DiscoveredExtension, ProviderExpansionResult } from "./provider.js";
import { discoverExtensionInstances } from "./discover-extensions.js";

export interface ProviderConfig {
  /** Unique provider ID (e.g. "rbac"). */
  id: string;

  /** Template definitions this provider contributes to the registry. */
  templates: ExtensionTemplateDef[];

  /** Expand discovered instances into resource mutations. */
  expand(resources: ResourceDef[], discovered: DiscoveredExtension[]): ProviderExpansionResult;

  /** Namespaces this provider owns (excluded from unified JSON schema, etc.). */
  ownedNamespaces?: string[];

  /** Cost per extension instance for complexity budget (default: 1). */
  costPerInstance?: number;

  /** Param key used for namespace cross-checking (e.g. "application"). */
  applicationParamKey?: string;

  /** Param key used for permission metadata (e.g. "v2Perm"). */
  permissionParamKey?: string;

  /** Optional: wire scaffold relations needed before cascade-delete expansion. */
  onBeforeCascadeDelete?(resources: ResourceDef[]): ResourceDef[];

  /**
   * Optional custom discover implementation. If omitted, discovery is
   * auto-generated by scanning for template instances in the compiled program.
   */
  discover?(program: Program): DiscoveredExtension[];
}

/**
 * Validates that all required keys are present non-empty strings in a
 * discovered extension's raw params, then returns the typed object.
 * Returns null if any key is missing or empty.
 */
function parseParams<T>(
  params: Record<string, string>,
  requiredKeys: readonly string[],
): T | null {
  for (const key of requiredKeys) {
    if (typeof params[key] !== "string" || params[key] === "") return null;
  }
  return params as unknown as T;
}

/**
 * Extracts and validates typed params from discovered extensions in one pass.
 * Drops entries with missing/empty required keys. An optional `validate`
 * predicate allows provider-specific checks (e.g., verb allowlisting).
 */
export function validParams<T>(
  discovered: DiscoveredExtension[],
  requiredKeys: readonly string[],
  validate?: (parsed: T) => boolean,
): T[] {
  const results: T[] = [];
  for (const d of discovered) {
    const parsed = parseParams<T>(d.params, requiredKeys);
    if (parsed === null) continue;
    if (validate && !validate(parsed)) continue;
    results.push(parsed);
  }
  return results;
}

/**
 * Creates a full ExtensionProvider from a minimal config.
 *
 * Auto-generates discover() by scanning for instances of the provider's
 * templates in the compiled TypeSpec program. Provider authors only need
 * to supply expand() and optionally onBeforeCascadeDelete().
 */
export function defineProvider(config: ProviderConfig): ExtensionProvider {
  const {
    id,
    templates,
    expand,
    ownedNamespaces,
    costPerInstance,
    applicationParamKey,
    permissionParamKey,
    onBeforeCascadeDelete,
  } = config;

  const discover = config.discover ?? function autoDiscover(program: Program): DiscoveredExtension[] {
    const discovered: DiscoveredExtension[] = [];
    for (const template of templates) {
      const { results } = discoverExtensionInstances(program, template);
      for (const params of results) {
        if (Object.keys(params).length === template.paramNames.length) {
          discovered.push({ kind: template.templateName, params });
        }
      }
    }
    return discovered;
  };

  return {
    id,
    templates,
    discover,
    expand,
    ownedNamespaces,
    costPerInstance,
    applicationParamKey,
    permissionParamKey,
    onBeforeCascadeDelete,
  };
}
